{{ if eq .Values.operation "execute" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: execute
  labels:
    app: execute
    part-of: neon
spec:
  template:
    spec:
      containers:
        - name: execute
          image: ghcr.io/umd-dslam/benchbase:latest
          command:
            - /bin/sh
            - -c
          args:
            - |
              /benchbase/entrypoint.sh --bench {{ .Values.benchmark }}           \
                                       --config /config/config.xml               \
                                       --execute=true                            \
                                       --interval-monitor 1000                   \
                                       --json-histograms results/histograms.json | tee results/log.txt 

              /usr/bin/mc alias set minio http://hub.global:9000 minioadmin minioadmin
              /usr/bin/mc cp ./results/* minio/neon/{{ default .Values.timestamp .Values.tag }}/{{ include "namespaceId" . }}-{{ .Release.Namespace }}/
          volumeMounts:
            - name: config
              mountPath: /config
      restartPolicy: Never
      volumes:
        - name: config
          configMap:
            name: benchbase-config
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - client
            - weight: 1
              preference:
                {{- include "nodesInCurrentRegion" . | indent 16 }}
{{ end }}