{{ if eq .Release.Namespace "global" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: hub-config
  labels:
    app: hub-config
    part-of: neon
data:
  prometheus.yaml: |
    global:
      scrape_interval: 2s

    scrape_configs:
      - job_name: pageserver
        static_configs:
          - targets:
          {{- range $r := .Values.ordered_namespaces }}
            - pageserver.{{ $r }}:9898
          {{- end }}

      # - job_name: compute
      #   static_configs:
      #     - targets: 
      #     {{- range $r := .Values.ordered_namespaces }}
      #       - compute.{{ $r }}:9187
      #     {{- end }}

      - job_name: safekeeper
        static_configs:
          - targets:
          {{- range $r := .Values.ordered_namespaces }}
            - safekeeper-0.safekeeper.{{ $r }}:7676
          {{- end }}

      - job_name: xactserver
        static_configs:
          - targets:
          {{- range $r := .Values.ordered_namespaces }}
            - xactserver.{{ $r }}:8080
          {{- end }}
      
      - job_name: pushgateway
        static_configs:
          - targets:
            - localhost:9091

    remote_write:
      - url: {{ .Values.prometheus.remote_write.url }}
        basic_auth:
          username: {{ .Values.prometheus.remote_write.basic_auth.username }}
          password: {{ .Values.prometheus.remote_write.basic_auth.password }}
        write_relabel_configs:
          - source_labels: [__name__]
            regex: '^go.*$'
            action: drop
          - source_labels: [__name__]
            regex: '^libmetrics.*$'
            action: drop
          - source_labels: [__name__]
            regex: '^pageserver_startup.*$'
            action: drop
          - source_labels: [__name__]
            regex: '^pageserver_io.*$'
            action: drop
          - source_labels: [__name__]
            regex: '^pageserver_basebackup.*$'
            action: drop
          - source_labels: [__name__]
            regex: '^pageserver_tenant.*$'
            action: drop
          - source_labels: [__name__]
            regex: '^pageserver_unexpected.*$'
            action: drop
          - source_labels: [__name__]
            regex: '^safekeeper_acceptor.*$|^safekeeper_backup.*$'
            action: drop
          - source_labels: [__name__]
            regex: '^safekeeper_broker.*$'
            action: drop
          - source_labels: [__name__]
            regex: '^safekeeper_persist.*$'
            action: drop
          - source_labels: [__name__]
            regex: '^safekeeper_timeline.*$'
            action: drop
          - source_labels: [__name__]
            regex: '^safekeeper_pg.*$'
            action: drop
          - source_labels: [__name__]
            regex: '^safekeeper_write.*$'
            action: drop
          - source_labels: [__name__]
            regex: '^safekeeper_flush.*$'
            action: drop
{{ end }}