{{ if eq .Release.Namespace "global" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: hub-config
  labels:
    app: hub-config
    part-of: neon
data:
  prometheus.yaml: |
    global:
      scrape_interval: 2s

    scrape_configs:
      - job_name: pageserver
        static_configs:
          - targets:
          {{- range $r := .Values.ordered_namespaces }}
            - pageserver.{{ $r }}:9898
          {{- end }}

      # - job_name: compute
      #   static_configs:
      #     - targets: 
      #     {{- range $r := .Values.ordered_namespaces }}
      #       - compute.{{ $r }}:9187
      #     {{- end }}

      - job_name: xactserver
        static_configs:
          - targets:
          {{- range $r := .Values.ordered_namespaces }}
            - xactserver.{{ $r }}:8080
          {{- end }}
{{ end }}