{{ if eq .Release.Namespace "global" }}
apiVersion: v1
kind: Service
metadata:
  name: hub
  labels:
    app: hub
    part-of: neon
spec:
  ports:
    - name: minio-api
      targetPort: minio-api
      port: 9000
    - name: minio-console
      targetPort: minio-console
      port: 9001
    - name: prometheus
      targetPort: prometheus
      port: 9090
    - name: grafana
      targetPort: grafana
      port: 3000
  selector:
    app: hub
  # In general, service IPs and pod IPs come from different CIDR ranges.
  # In AWS, the pods are assigned IPs direclty from the VPC subnet whereas
  # the service IPs are assigned from a virtual range, which is not easily
  # accessible from a different region. The VPC subnets, however, can be easily
  # routed between regions. Therefore, we use a headless service (setting 
  # clusterIP to None) to expose the pod IPs directly instead of using the service IP.
  clusterIP: None
---
{{ if .Values.hub_ebs_volume_id }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hub-data-aws
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: {{ .Values.hub_ebs_volume_id }}
    fsType: ext4
  storageClassName: ""
  claimRef:
    name: hub-data
    namespace: global
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hub-data
spec:
  storageClassName: ""
  volumeName: hub-data-aws
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
{{ end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub
  labels:
    app: hub
    component: hub
    part-of: neon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub
  template:
    metadata:
      labels:
        app: hub
        component: hub
        part-of: neon
    spec:
      securityContext:
        fsGroup: 2000
      containers:
        - name: minio
          image: quay.io/minio/minio:RELEASE.2022-11-17T23-20-09Z
          args: 
            - server
            - /data/minio
            - --console-address
            - :9001
          volumeMounts:
            - name: hub-data
              mountPath: /data
            - name: hub-config
              mountPath: /config
          ports: 
            - name: minio-api
              containerPort: 9000
            - name: minio-console
              containerPort: 9001
        - name: prometheus
          image: prom/prometheus:v2.28.1
          args:
            - --config.file=/config/prometheus.yaml
            - --storage.tsdb.path=/data/prometheus
          ports:
            - name: prometheus
              containerPort: 9090
          volumeMounts:
            - name: hub-data
              mountPath: /data  
            - name: hub-config
              mountPath: /config
        - name: grafana
          image: ctring/grafana:slogora
          imagePullPolicy: Always
          ports:
            - name: grafana
              containerPort: 3000
      volumes:
        - name: hub-config
          configMap:
            name: hub-config
        - name: hub-data
          {{ if .Values.hub_ebs_volume_id }}
          persistentVolumeClaim:
            claimName: hub-data
          {{ else }}
          emptyDir:
            sizeLimit: 2Gi
          {{ end }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - {{- include "nodesInCurrentRegion" . | indent 18 }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: hub
                    operator: In
                    values:
                      - all
                      - hub
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - pageserver
                topologyKey: "kubernetes.io/hostname"
{{ end }}