{{ if eq .Release.Namespace "global" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: init-data
  labels:
    app: init-data
    part-of: neon
spec:
  template:
    spec:
      containers:
        - name: init-data
          image: ctring/neonctl:latest
          command:
            - /bin/sh
            - -c
          args:
            - |
              # Generate the base data for the cluster
              python3 /tools/neonctl.py   \
                --no-xactserver           \
                --neon-dir /usr/local/bin \
                --pg-dir /usr/local       \
                create .                  \
                --keep-neon               \
                --num-regions {{ sub (len .Values.ordered_namespaces) 1 }}

              # Wait until minio is ready then upload the data
              until (/usr/bin/mc alias set minio http://hub:9000 minioadmin minioadmin) do
                echo 'Waiting to start minio...' && sleep 1
              done
              mc mb minio/neon
              mc rm -r --force minio/neon/.neon
              mc cp -r ./r0/.neon minio/neon/
              touch .done
              mc cp .done minio/neon/.neon/
      restartPolicy: Never
{{ end }}