apiVersion: v1
kind: Service
metadata:
  name: pageserver
  labels:
    app: pageserver
    component: storage
    part-of: neon
spec:
  ports:
    - name: postgres
      targetPort: postgres
      port: 6400
    - name: http
      targetPort: http
      port: 9898
  selector:
    app: pageserver
  # In general, service IPs and pod IPs come from different CIDR ranges.
  # In AWS, the pods are assigned IPs direclty from the VPC subnet whereas
  # the service IPs are assigned from a virtual range, which is not easily
  # accessible from a different region. The VPC subnets, however, can be easily
  # routed between regions. Therefore, we use a headless service (setting 
  # clusterIP to None) to expose the pod IPs directly instead of using the service IP.
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pageserver
  labels:
    app: pageserver
    component: storage
    part-of: neon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pageserver
  template:
    metadata:
      labels:
        app: pageserver
        component: storage
        part-of: neon
    spec:
      containers:
        - name: pageserver
          image: ctring/neon:latest
          command:
            - /bin/sh
            - -ecx
          args:
            - |
              until (/usr/bin/mc alias set minio http://hub.global:9000 minioadmin minioadmin) do
                  echo 'Waiting to start minio...' && sleep 1
              done
              until (/usr/bin/mc stat minio/neon/.neon/.done) do
                  echo 'Waiting for the base data...' && sleep 1
              done
              rm -rf /data/.neon
              /usr/bin/mc cp -r minio/neon/.neon /data
              /usr/local/bin/pageserver -D /data/.neon/                                            \
                                        -c "broker_endpoint='http://storage-broker.global:50051'"  \
                                        -c "listen_pg_addr='0.0.0.0:6400'"                         \
                                        -c "listen_http_addr='0.0.0.0:9898'                        \
                                        -c "page_cache_size=13107200"
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - name: postgres
              containerPort: 6400
            - name: http
              containerPort: 9898
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 40Gi
      affinity:
        nodeAffinity:
          # This rule is useful when we deploy all "regions" in the same physical region, making
          # them not have a division based on cluster context. Therefore, we need to rely on the
          # node labels to separate them by regions.
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - {{- include "nodesInCurrentRegion" . | indent 20 }}
          {{- if eq .Release.Namespace "global" }}
          # In the global region, everything is placed on the "hub" node
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - hub
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - pageserver
          {{- end }}
        podAntiAffinity:
          # This is to ensure that pageserver pods are not scheduled on the same node.
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - pageserver
                namespaceSelector:
                  matchExpressions:
                    - key: part-of
                      operator: In
                      values:
                      - neon
                topologyKey: "kubernetes.io/hostname"