apiVersion: v1
kind: Service
metadata:
  name: safekeeper
  labels:
    app: safekeeper
    component: storage
    part-of: neon
spec:
  ports:
    - name: postgres
      targetPort: postgres
      port: 5454
    - name: http
      targetPort: http
      port: 7676
  selector:
    app: safekeeper
  # In general, service IPs and pod IPs come from different CIDR ranges.
  # In AWS, the pods are assigned IPs direclty from the VPC subnet whereas
  # the service IPs are assigned from a virtual range, which is not easily
  # accessible from a different region. The VPC subnets, however, can be easily
  # routed between regions. Therefore, we use a headless service (setting 
  # clusterIP to None) to expose the pod IPs directly instead of using the service IP.
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: safekeeper
  labels:
    app: safekeeper
    component: storage
    part-of: neon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safekeeper
  template:
    metadata:
      labels:
        app: safekeeper
        component: storage
        part-of: neon
    spec:
      containers:
        - name: safekeeper
          image: ctring/neon:latest
          args:           
            - safekeeper
            - --id=1
            - --datadir=/data
            - --listen-pg=safekeeper.{{ .Release.Namespace }}:5454
            - --listen-http=0.0.0.0:7676
            - --broker-endpoint=http://storage-broker.global:50051
          ports:
            - name: postgres
              containerPort: 5454
            - name: http
              containerPort: 7676
      hostAliases:
        - ip: "0.0.0.0"
          hostnames:
            - safekeeper.{{ .Release.Namespace }}
      restartPolicy: Always
      affinity:
        nodeAffinity:
          # Prefer to schedule safekeeper pods on nodes with the role "safekeeper".
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: role
                operator: In
                values:
                - server
        podAntiAffinity:
          # This is to ensure that safekeeper pods are not scheduled on the same node.
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - safekeeper
                topologyKey: "kubernetes.io/hostname"
          {{- if ne .Release.Namespace "global" }}
          # We prefer that safekeeper pods are not scheduled on the same node as pageserver, xactserver, or compute.
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - pageserver
                        - xactserver  
                        - compute
                topologyKey: "kubernetes.io/hostname"
          {{- end }}

