{{ if eq .Release.Namespace "global" }}
apiVersion: v1
kind: Service
metadata:
  name: storage-broker
  labels:
    app: storage-broker
    component: storage
    part-of: neon
spec:
  ports:
    - name: api
      targetPort: api
      port: 50051
  selector:
    app: storage-broker
  # In general, service IPs and pod IPs come from different CIDR ranges.
  # In AWS, the pods are assigned IPs direclty from the VPC subnet whereas
  # the service IPs are assigned from a virtual range, which is not easily
  # accessible from a different region. The VPC subnets, however, can be easily
  # routed between regions. Therefore, we use a headless service (setting 
  # clusterIP to None) to expose the pod IPs directly instead of using the service IP.
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-broker
  labels:
    app: storage-broker
    component: storage
    part-of: neon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-broker
  template:
    metadata:
      labels:
        app: storage-broker
        component: storage
        part-of: neon
    spec:
      containers:
        - name: storage-broker
          image: ctring/neon:latest
          args:
            - storage_broker
            - --listen-addr=0.0.0.0:50051
          ports:
            - name: api
              containerPort: 50051
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - {{- include "nodesInCurrentRegion" . | indent 20 }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - hub
{{ end }}