apiVersion: v1
kind: ConfigMap
metadata:
  name: compute-config
  namespace: global
  labels:
    app: compute-config
    component: compute
    part-of: neon
data:
  compute.sh: |
    #!/bin/bash
    set -eux

    # Generate a random tenant or timeline ID
    #
    # Takes a variable name as argument. The result is stored in that variable.
    generate_id() {
        local -n resvar=$1
        printf -v resvar '%08x%08x%08x%08x' $SRANDOM $SRANDOM $SRANDOM $SRANDOM
    }

    PG_VERSION=${PG_VERSION:-14}

    SPEC_FILE_ORG=/config/spec-template.json
    SPEC_FILE=/data/spec.json

    echo "Waiting pageserver become ready."
    while ! nc -z pageserver 6400; do
        sleep 1;
    done
    echo "Page server is ready."

    echo "Create a tenant and timeline"
    generate_id tenant_id
    PARAMS=(
        -sb 
        -X POST
        -H "Content-Type: application/json"
        -d "{\"new_tenant_id\": \"${tenant_id}\"}"
        http://pageserver:9898/v1/tenant/
    )
    result=$(curl "${PARAMS[@]}")
    echo $result | jq .

    generate_id timeline_id
    PARAMS=(
        -sb 
        -X POST
        -H "Content-Type: application/json"
        -d "{\"new_timeline_id\": \"${timeline_id}\", \"pg_version\": ${PG_VERSION}}"
        "http://pageserver:9898/v1/tenant/${tenant_id}/timeline/"
    )
    result=$(curl "${PARAMS[@]}")
    echo $result | jq .

    echo "Overwrite tenant id and timeline id in spec file"
    sed "s/TENANT_ID/${tenant_id}/" ${SPEC_FILE_ORG} > ${SPEC_FILE}
    sed -i "s/TIMELINE_ID/${timeline_id}/" ${SPEC_FILE}

    cat ${SPEC_FILE}
  spec-template.json: |
    {
        "format_version": 1.0,

        "timestamp": "2022-10-12T18:00:00.000Z",
        "operation_uuid": "0f657b36-4b0f-4a2d-9c2e-1dcd615e7d8c",

        "cluster": {
            "cluster_id": "neon",
            "name": "neon",
            "state": "restarted",
             "roles": [
                {
                    "name": "cloud_admin",
                    "encrypted_password": "b093c0d3b281ba6da1eacc608620abd8",
                    "options": null
                }
            ],
            "databases": [
            ],
            "settings": [
                {
                    "name": "fsync",
                    "value": "off",
                    "vartype": "bool"
                },
                {
                    "name": "hot_standby",
                    "value": "on",
                    "vartype": "bool"
                },
                {
                    "name": "wal_log_hints",
                    "value": "on",
                    "vartype": "bool"
                },
                {
                    "name": "log_connections",
                    "value": "on",
                    "vartype": "bool"
                },
                {
                    "name": "port",
                    "value": "55433",
                    "vartype": "integer"
                },
                {
                    "name": "shared_buffers",
                    "value": "8GB",
                    "vartype": "string"
                },
                {
                    "name": "max_connections",
                    "value": "100",
                    "vartype": "integer"
                },
                {
                    "name": "listen_addresses",
                    "value": "0.0.0.0",
                    "vartype": "string"
                },
                {
                    "name": "max_wal_senders",
                    "value": "10",
                    "vartype": "integer"
                },
                {
                    "name": "max_replication_slots",
                    "value": "10",
                    "vartype": "integer"
                },
                {
                    "name": "wal_sender_timeout",
                    "value": "5s",
                    "vartype": "string"
                },
                {
                    "name": "wal_keep_size",
                    "value": "0",
                    "vartype": "integer"
                },
                {
                    "name": "password_encryption",
                    "value": "md5",
                    "vartype": "enum"
                },
                {
                    "name": "restart_after_crash",
                    "value": "off",
                    "vartype": "bool"
                },
                {
                    "name": "synchronous_standby_names",
                    "value": "walproposer",
                    "vartype": "string"
                },
                {
                    "name": "shared_preload_libraries",
                    "value": "neon",
                    "vartype": "string"
                },
                {
                    "name": "neon.safekeepers",
                    "value": "safekeeper:5454",
                    "vartype": "string"
                },
                {
                    "name": "neon.timeline_id",
                    "value": "TIMELINE_ID",
                    "vartype": "string"
                },
                {
                    "name": "neon.tenant_id",
                    "value": "TENANT_ID",
                    "vartype": "string"
                },
                {
                    "name": "neon.pageserver_connstring",
                    "value": "host=pageserver port=6400",
                    "vartype": "string"
                },
                {
                    "name": "max_replication_write_lag",
                    "value": "500MB",
                    "vartype": "string"
                },
                {
                    "name": "max_replication_flush_lag",
                    "value": "10GB",
                    "vartype": "string"
                },
                {
                    "name": "track_counts",
                    "value": "off",
                    "vartype": "bool"
                },
                {
                    "name": "track_io_timing",
                    "value": "off",
                    "vartype": "bool"
                },
                {
                    "name": "max_pred_locks_per_transaction",
                    "value": "256",
                    "vartype": "integer"
                },
                {
                    "name": "temp_buffers",
                    "value": "4096",
                    "vartype": "integer"
                }
            ]
        },

        "delta_operations": [
        ]
    }
 