apiVersion: v1
kind: Service
metadata:
  name: hub
  namespace: global
  labels:
    app: hub
spec:
  ports:
    - name: minio-api
      targetPort: minio-api
      port: 9000
    - name: minio-console
      targetPort: minio-console
      port: 9001
  selector:
    app: hub
  # In general, service IPs and pod IPs come from different CIDR ranges.
  # In AWS, the pods are assigned IPs direclty from the VPC subnet whereas
  # the service IPs are assigned from a virtual range, which is not easily
  # accessible from a different region. The VPC subnets, however, can be easily
  # routed between regions. Therefore, we use a headless service (setting 
  # clusterIP to None) to expose the pod IPs directly instead of using the service IP.
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub
  namespace: global
  labels:
    app: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub
  template:
    metadata:
      labels:
        app: hub
    spec:
      securityContext:
        fsGroup: 2000
      containers:
        - name: minio
          image: quay.io/minio/minio:RELEASE.2022-11-17T23-20-09Z
          args: 
            - server
            - /data/minio
            - --console-address
            - :9001
          volumeMounts:
            - name: hub-data
              mountPath: /data
          ports: 
            - name: minio-api
              containerPort: 9000
            - name: minio-console
              containerPort: 9001
      volumes:
        - name: hub-data
          emptyDir:
            sizeLimit: 4Gi