apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: yb-multiregion
  region: {{ .Values.region }}

vpc:
  subnets:
    public:
      {{ range $key, $value := get .Values.subnets .Values.region -}}
      {{ $key }}: { id: {{ $value }} }
      {{ end }}
managedNodeGroups:
  - name: standard-workers
    subnets:
      - {{ get .Values.subnets .Values.region | values | first }}
    instanceType: {{ get .Values.instance_types "standard-workers" }}
    spot: {{ .Values.spot.standard_worker }}
    desiredCapacity: 1
    securityGroups:
      attachIDs:
        - {{ get .Values.security_groups .Values.region }}
    labels:
      role: standard-worker
      region: {{ .Values.region }}

  - name: clients
    subnets:
      - {{ get .Values.subnets .Values.region | values | first }}
    instanceType: {{ get .Values.instance_types "client" }}
    spot: {{ .Values.spot.client }}
    desiredCapacity: 1
    securityGroups:
      attachIDs:
        - {{ get .Values.security_groups .Values.region }}
    labels:
      role: client
      region: {{ .Values.region }}

{{ if and (.Values.aws_ebs_csi_driver) (eq .Values.region .Values.global_region) -}}
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      roleName: AmazonEKS_EBS_CSI_DriverRole
      roleOnly: true
      wellKnownPolicies:
        ebsCSIController: true

addons:
  - name: aws-ebs-csi-driver
    serviceAccountRoleARN: arn:aws:iam::970400548469:role/AmazonEKS_EBS_CSI_DriverRole
{{ end }}