version: '3.8'

services:
  minio:
    restart: always
    image: quay.io/minio/minio:RELEASE.2022-11-17T23-20-09Z
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --address :9000 --console-address ":9001"
