[package]
name = "xactserver"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
bb8 = "0.8.0"
bit-set = "0.5.3"
bytes = { version = "1.0.1", features = ["serde"] }
clap = { version = "3.2.7", features = ["derive"] }
env_logger = "0.9.0"
futures = "0.3.17"
log = "0.4.14"
prost = "0.10"
tonic = "0.7"
tokio = { version = "1.19.2", features = ["rt-multi-thread", "macros", "sync"] }
tokio-stream = "0.1"
zenith_utils = { git = "https://github.com/zenithdb/zenith.git", package = "utils" }
tokio_postgres = { git = "https://github.com/zenithdb/rust-postgres.git", branch = "replication", package = "tokio-postgres" }

[build-dependencies]
tonic-build = "0.7"
