version: '3.8'

configs:
  prometheus:
    file: ./prometheus.yml

services:
  minio:
    restart: always
    image: quay.io/minio/minio:RELEASE.2022-11-17T23-20-09Z
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --address :9000 --console-address ":9001"
    volumes:
      - /media/data/minio:/data

  prometheus:
    restart: always
    image: prom/prometheus:latest
    network_mode: host
    ports:
      - 9090:9090
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
    volumes:
      - /media/data/prometheus:/prometheus

  prometheus-pushgateway:
    restart: always
    image: prom/pushgateway:latest
    network_mode: host
    ports:
      - 9091:9091

  grafana:
    restart: always
    image: ctring/grafana:sunstorm
    network_mode: host
    ports:
      - 3000:3000
    volumes:
      - /media/data/grafana:/var/lib/grafana