global:
  scrape_interval: 2s 

scrape_configs:
  - job_name: pageserver
    static_configs:
      - targets:
        - 10.0.0.10:9898
        - 10.1.0.10:9898
        - 10.8.0.10:9898

  - job_name: safekeeper
    static_configs:
      - targets:
        - 10.0.0.20:7676
        - 10.1.0.20:7676
        - 10.8.0.20:7676

  - job_name: xactserver
    static_configs:
      - targets: 
        - 10.0.0.20:8080
        - 10.1.0.20:8080
        - 10.8.0.20:8080

  - job_name: pushgateway
    honor_labels: false
    scrape_interval: 1s
    static_configs:
      - targets:
        # Use 30091 if the pushgateway is deployed on Kubernetes
        - localhost:9091

remote_write:
  - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
    basic_auth:
      username: 951279
      password: 