# AWS regions to deploy to.
# Per-region configurations:
# - id: The ID of the region. 
# - context: The context of the region. If not set, it will be inferred from the region name and the ".kube/config" file.
# - benchbase_instances: The number of benchbase instances to deploy for benchmark execution.
# - target_address_and_database: The address of the database to connect to. If not set, the target address is "compute" and the database is "postgres".
# - warmup: The warmup time in seconds. If not set, the warmup time is 0.
regions:
  us-east-1:
    id: 1
    # context: minikube
    benchbase_instances: 2

    # sunstorm
    # target_address_and_database: 10.0.0.30:55433/postgres
    # warmup: 0

    # aurora
    # target_address_and_database: master.coh7r4lbsfrp.us-east-1.rds.amazonaws.com:5432/postgres
    # warmup: 0

    # yugabyte
    # target_address_and_database: 10.0.0.10:5433/postgres;10.0.0.20:5433/postgres;10.0.0.30:5433/postgres
    # warmup: 0
  us-east-2:
    id: 2 
    # context: minikube
    benchbase_instances: 1

    # sunstorm
    # target_address_and_database: 10.1.0.30:55433/postgres
    # warmup: 0

    # aurora
    # target_address_and_database: follower.cc0cnngq1jy5.us-east-2.rds.amazonaws.com:5432/postgres
    # warmup: 0

    # yugabyte
    # target_address_and_database: 10.1.0.10:5433/postgres;10.1.0.20:5433/postgres;10.1.0.30:5433/postgres
    # warmup: 0
  us-west-1:
    id: 3
    # context: minikube
    benchbase_instances: 1

    # sunstorm
    # target_address_and_database: 10.8.0.30:55433/postgres
    # warmup: 0

    # aurora
    # target_address_and_database: follower.cm27bilwogwz.us-west-1.rds.amazonaws.com:5432/postgres
    # warmup: 0

    # yugabyte
    # target_address_and_database: 10.8.0.10:5433/postgres;10.8.0.20:5433/postgres;10.8.0.30:5433/postgres
    # warmup: 0

# The region that contains the global resources. This region can
# be one of the regions listed above, or a different region.
global_region: us-east-1
# global_region_context: minikube

# sunstorm
# global_region_target_address_and_database: 10.0.0.5:55433/postgres

# aurora
# global_region_target_address_and_database: master.coh7r4lbsfrp.us-east-1.rds.amazonaws.com:5432/postgres

# yugabyte
# global_region_target_address_and_database: 10.0.0.10:5433/postgres
