# AWS regions to deploy to. If the context of a region is not set,
# it will be inferred from the region name and the ".kube/config" file.
regions:
  us-east-1:
    id: 1
    # context: minikube
    # If this is specified, the benchmark will send workload to the given target
    # instead of the default "compute" service.
    # target_address_and_database: host.minikube.internal:55433/postgres
    warmup: 0
  us-east-2:
    id: 2 
    # context: minikube
    # target_address_and_database: host.minikube.internal:55433/postgres
    warmup: 0
  us-west-1:
    id: 3
    # context: minikube
    # target_address_and_database: host.minikube.internal:55433/postgres
    warmup: 0
  # eu-west-1:
  #   id: 4
    # context: minikube
    # target_address_and_database: host.minikube.internal:55433/postgres
    # warmup: 0

# The region that contains the global resources. This region can
# be one of the regions listed above, or a different region.
global_region: us-east-1
# global_region_context: minikube
# global_region_target_address_and_database: host.minikube.internal:55433/postgres
