# AWS regions to deploy to. If the context of a region is not set,
# it will be inferred from the region name and the ".kube/config" file.
regions:
  us-east-1:
    id: 1
    context: ctring@neon.us-east-1.eksctl.io
  us-east-2:
    id: 2
    context: ctring@neon.us-east-1.eksctl.io
  # us-west-1:
  #   id: 3
    # context: minikube
  # eu-west-1:
  #   id: 4
    # context: minikube
  # us-west-2:
  #   id: 5
  #   # context: minikube
  # eu-west-2:
  #   id: 6
  #   # context: minikube

# The region that contains the global resources. This region can
# be one of the regions listed above, or a different region.
global_region: us-east-1
# global_region_context: minikube
