apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  labels:
    app: pushgateway
    part-of: neon
spec:
  type: NodePort
  ports:
    - name: pushgateway
      targetPort: pushgateway
      port: 9091
      nodePort: 9091
  selector:
    app: pushgateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  labels:
    app: pushgateway
    component: pushgateway
    part-of: neon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
        component: pushgateway
        part-of: neon
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:latest
          ports:
            - name: pushgateway
              containerPort: 9091
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - client