# AWS regions to deploy to
regions:
  - us-east-1
  - us-east-2
  - us-west-1

# The region that contains the global resources. This region can
# be one of the regions listed above, or a different region.
global_region: us-east-1