apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: neon
  region: {{ .Values.region }}

{{- $subnets := get .Values.subnets .Values.region }}
vpc:
  subnets:
    public:
      {{ range $key, $value := $subnets -}}
      {{ $key }}: { id: {{ $value }} }
      {{ end }}

{{- $node_subnet := get $subnets (printf "%sa" .Values.region) }}
nodeGroups:
  {{- if not (empty (get .Values.instance_types "compute")) }}
  - name: computes
    subnets:
      - {{ $node_subnet }}
    {{- if .Values.spot.compute }}
    instancesDistribution:
      instanceTypes: 
        - {{ get .Values.instance_types "compute" }}
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotAllocationStrategy: "capacity-optimized"
    {{- else }}
    instanceType: {{ get .Values.instance_types "compute" }}
    {{- end }}
    desiredCapacity: 1
    securityGroups:
      attachIDs:
        - {{ get .Values.security_groups .Values.region }}
    labels:
      role: compute
      region: {{ .Values.region }}
  {{- end }}
  {{- if not (empty (get .Values.instance_types "pageserver")) }}
  - name: pageservers
    subnets:
      - {{ $node_subnet }}
    {{- if .Values.spot.pageserver }}
    instancesDistribution:
      instanceTypes: 
        - {{ get .Values.instance_types "pageserver" }}
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotAllocationStrategy: "capacity-optimized"
    {{- else }}
    instanceType: {{ get .Values.instance_types "pageserver" }}
    {{- end }}
    desiredCapacity: 1
    securityGroups:
      attachIDs:
        - {{ get .Values.security_groups .Values.region }}
    labels:
      role: pageserver
      region: {{ .Values.region }}
  {{- end }}
managedNodeGroups:
  {{- if not (empty (get .Values.instance_types "client")) }}
  - name: clients
    subnets:
      - {{ $node_subnet }}
    instanceType: {{ get .Values.instance_types "client" }}
    spot: {{ .Values.spot.client }}
    desiredCapacity: 1
    securityGroups:
      attachIDs:
        - {{ get .Values.security_groups .Values.region }}
    {{- if .Values.ssh_key_name }}
    ssh:
      allow: true
      publicKeyName: {{ .Values.ssh_key_name }}
    {{- end }}
    labels:
      role: client
      region: {{ .Values.region }}
  {{- end }}
  {{ if eq .Values.region .Values.global_region }}
  {{- if not (empty (get .Values.instance_types "hub")) }}
  - name: hub
    subnets:
      - {{ $node_subnet }}
    instanceType: {{ get .Values.instance_types "hub" }}
    spot: {{ .Values.spot.hub }}
    desiredCapacity: 1
    securityGroups:
      attachIDs:
        - {{ get .Values.security_groups .Values.region }}
    labels:
      role: hub
      region: {{ .Values.region }}
  {{- end }}
  {{- end }}
