# The first region should always be the global region.
# If you run deploy.py, this value will be set automatically.
regions:
  - global
  - us-east-1

# Number of safekeeper replicas
safekeeper_replicas: 1

# EBS volume ID to store global data like metrics, minio, etc.
# If not specified, no EBS volume will be used.
# center_ebs_volume_id: vol-045f146f990cbcaa4