# If you run deploy.py, this value will be set automatically.
namespaces:
  global:
    region: us-east-1
  us-east-1:
    region: us-east-1

# An ordered list of the namespaces. 
# If you run deploy.py, this value will be set automatically.
ordered_namespaces:
  - global
  - us-east-1

# Number of safekeeper replicas
safekeeper_replicas: 1

# EBS volume ID to store global data like metrics, minio, etc.
# No EBS volume will be used if this is empty. If you run deploy.py,
# this value will be set automatically.
hub_ebs_volume_id: null