# eksctl create cluster -f eks/eu-west-1.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: neon
  region: eu-west-1

vpc:
  subnets:
    public:
      eu-west-1a: { id: subnet-0ffc60f2e1a784c05 }
      eu-west-1b: { id: subnet-097b92d96accfde20 }
      eu-west-1c: { id: subnet-0765b6609bf1ab069 }

managedNodeGroups:
  - name: servers
    subnets:
      - eu-west-1a
    spot: false
    instanceType: r5.4xlarge
    desiredCapacity: 1
    securityGroups:
      attachIDs:
        - sg-0af119315a40fa0f9
    labels:
      role: server
      region: eu-west-1
  # - name: safekeepers
  #   subnets:
  #     - eu-west-1a
  #   spot: false
  #   instanceType: c5.xlarge
  #   desiredCapacity: 1
  #   securityGroups:
  #     attachIDs:
  #       - sg-0af119315a40fa0f9
  #   labels:
  #     role: safekeeper
  #     region: eu-west-1
  - name: clients
    subnets:
      - eu-west-1a
    spot: false
    instanceType: c5.xlarge
    desiredCapacity: 1
    securityGroups:
      attachIDs:
        - sg-0af119315a40fa0f9
    labels:
      role: client
      region: eu-west-1
