# eksctl create cluster -f eks/us-east-1.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: neon
  region: us-east-1

vpc:
  subnets:
    public:
      us-east-1a: { id: subnet-01ffdf1e8d2d11bce }
      us-east-1b: { id: subnet-0f2ae7a9189cd2786 }
      us-east-1c: { id: subnet-0346cab72850ef316 }

managedNodeGroups:
  - name: servers
    instanceType: c5.4xlarge
    spot: true
    desiredCapacity: 2
    securityGroups:
      attachIDs:
        - sg-018aeab319579349c
    labels:
      role: server
    tags:
      role: server
  - name: safekeepers
    instanceType: c5.2xlarge
    spot: true
    desiredCapacity: 1
    securityGroups:
      attachIDs:
        - sg-018aeab319579349c
    labels:
      role: safekeeper
    tags:
      role: safekeeper
  - name: clients
    instanceType: c5.2xlarge
    spot: true
    desiredCapacity: 1
    securityGroups:
      attachIDs:
        - sg-018aeab319579349c
    labels:
      role: client
    tags:
      role: client