# eksctl create cluster -f eks/us-west-2.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: neon
  region: us-west-2

vpc:
  subnets:
    public:
      us-west-2a: { id: subnet-0c7307ae51cd54955 }
      us-west-2b: { id: subnet-017e607e654b73f35 }
      us-west-2c: { id: subnet-06401fc941a2b272e }
      us-west-2d: { id: subnet-08b07ebe86eeeaffa }

managedNodeGroups:
  - name: servers
    instanceType: c5.4xlarge
    spot: true
    desiredCapacity: 1
    securityGroups:
      attachIDs:
        - sg-0f6f9d8fed793f085
    labels:
      role: server
      region: us-west-2
  - name: safekeepers
    instanceType: c5.2xlarge
    spot: true
    desiredCapacity: 1
    securityGroups:
      attachIDs:
        - sg-0f6f9d8fed793f085
    labels:
      role: safekeeper
      region: us-west-2
  - name: clients
    instanceType: c5.2xlarge
    spot: true
    desiredCapacity: 1
    securityGroups:
      attachIDs:
        - sg-0f6f9d8fed793f085
    labels:
      role: client
      region: us-west-2